version = 1

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "jest",
    "mocha"
  ]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "flow"
